name: Backend Deploy Only

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DATABASE_URL: mysql://root:UkIfcHzGHVfiJdIlNSvfaxTWzTGmYzYY@centerbeam.proxy.rlwy.net:55696/railway
  RAILWAY_DEPLOY_HOOK_URL: https://pos-cafe-production-41ef.up.railway.app/webhook/railway

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build & Deploy
        run: |
          cd backend
          npm install
          npm run build

      - name: Deploy to Railway
        run: curl -s "$RAILWAY_DEPLOY_HOOK_URL"

  migrate-seed:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v3
      - name: Migrate & Seed
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: |
          cd backend
          npm run migrate
          npm run seed
